defaults: &defaults
  host: 127.0.0.1
  port: 27017

development:
  <<: *defaults
  database: gitscm-library-development

test:
  <<: *defaults
  database: gitscm_test

# set these environment variables on your prod server
production:
  <<: *defaults
  database: gitscm-library
  username: <%= ENV['MONGO_USERNAME'] %>
  password: <%= ENV['MONGO_PASSWORD'] %>
